import { ArrowDown, Check, LockKeyhole, ShieldCheck, X } from "lucide-react";
import { CTASection, PageHero, SectionHeading, StatusTag, TrustStrip } from "@/components/site-shell";
import { initiatives } from "@/app/data";

export const metadata = { title: "Platform", description: "Prepare, Intake, the Patient Intelligence Brief, and a disciplined future roadmap." };

export default function Platform() {
  const layers = [
    { name: "Prepare", audience: "Patient-facing · free literacy and preparation", status: "development" as const, copy: "Restructures material the patient already has into a concise reason for request, stated AI assertions and sources, prioritized questions, and the patient’s goal for the visit.", boundary: "No diagnosis, treatment, or new medical conclusion." },
    { name: "Intake", audience: "Provider-facing · primary enterprise wedge", status: "development" as const, copy: "Receives, separates, labels, profiles, routes, and logs patient-originated AI before it enters the clinician’s normal review workflow.", boundary: "Every consequential classification remains subject to human review." },
    { name: "Vault", audience: "Patient-controlled longitudinal custody", status: "future" as const, copy: "A future permission and custody layer that begins only after Intake has paying health-system evidence and separate privacy, security, legal, operational, and governance work is complete.", boundary: "The Intake prototype is not a persistent patient record." },
  ];
  return <main id="main-content"><TrustStrip /><PageHero eyebrow="Platform" title="Three layers. One standard. A disciplined sequence." lede="Build provider-first. Stay patient-first. The enterprise Intake wedge is primary; patient preparation supports it; longitudinal custody remains deliberately deferred." status="development" />
    <section className="section"><div className="container layer-stack">{layers.map((layer, index) => <div key={layer.name} className={`layer-card layer-${index + 1}`}><div className="layer-number">0{index + 1}</div><div><div className="eyebrow-row"><span className="eyebrow">{layer.audience}</span><StatusTag status={layer.status} /></div><h2>{layer.name}</h2><p>{layer.copy}</p><div className="boundary"><ShieldCheck size={18} /><span><strong>Boundary:</strong> {layer.boundary}</span></div></div>{index < 2 && <ArrowDown className="layer-arrow" />}</div>)}</div></section>
    <section className="section intake-architecture"><div className="container"><SectionHeading eyebrow="Intake architecture" title="One enterprise workflow, not a collection of disconnected products." copy="Technical components remain subordinate to a clear job: make a submission inspectable and routable for an authorized clinical team." /><div className="architecture-grid">{["Approved submission intake", "Evidence & provenance", "Evidence-gap representation", "Submission relationship map", "Institution-approved protocols", "Five-dimension PGI profile", "Patient Intelligence Brief", "Clinical verification gateway", "Role-adaptive views", "Workflow analytics & audit"].map((x, i) => <article key={x}><span>{String(i + 1).padStart(2, "0")}</span><strong>{x}</strong></article>)}</div></div></section>
    <section className="section comparison-section"><div className="container"><SectionHeading eyebrow="Category discipline" title="What Patients Intelligence is—and is not." /><div className="is-not-grid"><article><span><Check /> Is</span>{["Clinical AI intake infrastructure", "A trust, translation, orchestration, and verification layer", "A model-neutral submission assurance workflow", "An open-standard strategy with enterprise implementation", "A bounded burden-reduction and communication opportunity"].map(x => <p key={x}><Check size={16} />{x}</p>)}</article><article><span><X /> Is not</span>{["A symptom checker or medical chatbot", "A telehealth provider or EHR replacement", "A pharmacy, marketplace, or advertising network", "A general-purpose model certification lab", "An autonomous clinical decision maker"].map(x => <p key={x}><X size={16} />{x}</p>)}</article></div></div></section>
    <section className="section gated-roadmap"><div className="container"><SectionHeading eyebrow="Deferred clinical intelligence protocols" title="Strong ideas stay gated until they earn re-entry." /><div className="roadmap-grid">{["Clinical Hypothesis Workspace", "Encounter Documentation Assistant", "Coding & Documentation Intelligence", "Care Coordination Workspace", "Extended Medication Intelligence Review"].map(x => <article key={x}><LockKeyhole /><StatusTag status="future" /><h3>{x}</h3></article>)}</div><div className="reentry"><h3>Three required re-entry gates</h3><ol><li><span>1</span>Intake proves the wedge with at least one paying health system.</li><li><span>2</span>Qualified counsel reviews that specific capability.</li><li><span>3</span>A recorded founder decision authorizes the scope change.</li></ol></div></div></section>
    <section className="section"><div className="container initiative-ledger"><SectionHeading eyebrow="Current truth status" title="Maturity is visible, not implied." /><div>{initiatives.map(item => <article key={item.name}><StatusTag status={item.status} /><h3>{item.name}</h3><p>{item.description}</p><small>Last verified · September 4, 2026</small></article>)}</div></div></section><CTASection /></main>;
}
