import Link from "next/link";
import { ArrowRight, Building2, GraduationCap, Microscope, Network, ShieldCheck } from "lucide-react";
import { CTASection, PageHero, SectionHeading, StatusTag } from "@/components/site-shell";

export const metadata = { title: "About", description: "Why Patients Intelligence exists, its NBG relationship, Massachusetts strategy, and team-building needs." };

export default function About() {
  return <main id="main-content"><PageHero eyebrow="About" title="Build the missing institution between patient AI and clinical care." lede="Our mission is to make patients more informed, clinicians better supported, and health systems more capable of trusted AI-enabled care." status="development" />
    <section className="section about-origin"><div className="container origin-grid"><div><span className="eyebrow">The founding observation</span><h2>Patient behavior changed before clinical intake infrastructure did.</h2></div><div><p>Patients increasingly arrive with AI-assisted analysis based on symptoms, records, reports, devices, and questions. Care teams still need a consistent way to tell what is sourced, what matches authorized records, what the patient reported, what the model inferred, and what requires human review.</p><blockquote>“The gap is not another medical chatbot. The gap is the connective tissue between patient-generated AI and professional medical judgment.”</blockquote></div></div></section>
    <section className="section ecosystem-section"><div className="container"><SectionHeading eyebrow="Staged ecosystem" title="A commercial implementation inside a public-benefit architecture." copy="Patients Intelligence is an NBG portfolio venture and umbrella for work connecting patients, clinicians, health systems, researchers, technology firms, advocates, and public agencies." /><div className="ecosystem-grid">{[[Building2, "Technologies", "Enterprise implementation and product development", "development"], [Network, "Network", "Planned standards stewardship, membership, and convening", "forming"], [Microscope, "Institute", "Planned research and independent validation", "forming"], [GraduationCap, "Academy", "Free patient literacy and future professional education", "future"], [ShieldCheck, "PGI Standard", "Open specification spanning the ecosystem", "draft"]].map(([Icon, name, copy, status]) => { const I = Icon as typeof Building2; return <article key={String(name)}><I /><h3>{String(name)}</h3><p>{String(copy)}</p><StatusTag status={status as "development" | "forming" | "future" | "draft"} /></article>; })}</div></div></section>
    <section className="section nbg-section"><div className="container nbg-grid"><div><span className="eyebrow">National Brand Group</span><h2>Built within an institution studio.</h2></div><div><p>Patients Intelligence is developed within National Brand Group, an institution and venture studio focused on building the systems emerging markets need to become credible, measurable, governable, and economically sustainable.</p><p>NBG currently holds the venture architecture and brand. Specialized clinical, informatics, privacy, security, research, and governance leadership must be recruited into the operating model.</p></div></div></section>
    <section className="section mass-section"><div className="container mass-grid"><div><div className="eyebrow-row"><span className="eyebrow">Massachusetts strategy</span><StatusTag status="proposed" /></div><h2>A concentrated ecosystem for responsible health AI.</h2><p>Massachusetts brings health systems, research universities, health AI assurance expertise, public AI programs, digital-health institutions, and policy leadership into one region.</p><p>The UMass Chan/MITRE Health AI Assurance Laboratory and Massachusetts AI initiatives are ecosystem context and possible future alignment—not current Patients Intelligence partners.</p><a href="https://masstech.org/news/health-ai-lab" target="_blank" rel="noreferrer">Read the MassTech announcement <ArrowRight size={15} /></a></div><aside><span>Upstream assurance</span><p>Is a model or product safe and fit for deployment?</p><ArrowRight /><span>Downstream intake assurance</span><p>What can a team responsibly understand from this specific patient-originated artifact?</p></aside></div></section>
    <section className="section team-section"><div className="container"><SectionHeading eyebrow="Team building" title="The next operating layer needs domain authority." /><div>{["Clinical co-founder or senior clinical leader", "Health informatics and FHIR expertise", "Health-system workflow leadership", "Patient-governance participation", "Regulatory counsel", "Privacy and security leadership", "Research collaborators"].map((x, i) => <article key={x}><span>0{i + 1}</span>{x}</article>)}</div><Link className="button button-primary" href="/contact?path=team">Discuss a leadership or collaboration role <ArrowRight size={17} /></Link></div></section><CTASection /></main>;
}
