import { PolicyPage } from "@/components/policy-page";

export const metadata = { title: "Terms of Use", description: "Interim terms governing this informational site and its inquiry forms." };

const sections: Array<[string, string]> = [
  ["1. Acceptance and scope", "These Interim Terms of Use govern this public informational website, its synthetic demonstrations, downloadable resources, and non-clinical inquiry forms. By using the site, you agree to these terms. If you do not agree, do not use it. A future clinical product, pilot, or institutional deployment would require separate agreements, review, and controls."],
  ["2. No medical advice or care relationship", "The site is not medical advice, diagnosis, treatment, a symptom checker, clinical intake channel, patient portal, emergency service, or substitute for a qualified healthcare professional. Use does not create a clinician-patient, fiduciary, legal, or other professional relationship. For a medical emergency, contact local emergency services."],
  ["3. No patient or health-information submissions", "Do not submit patient names, symptoms, diagnoses, records, images, identifiers, protected health information, or other sensitive health information through any public form, email link, or site feature. Public forms are solely for non-clinical organizational, research, partnership, and media inquiries. We may delete, quarantine, or decline to process prohibited material and are not responsible for a user's decision to submit it contrary to these terms."],
  ["4. Synthetic demonstration only", "All patient scenarios, records, scores, workflow events, and outputs shown in demonstrations are fictional and educational. They must not be used for clinical decisions, coding, coverage, triage, diagnosis, treatment, or patient-specific action."],
  ["5. Regulatory status and intended use", "Patients Intelligence is in development. No statement on this site determines that any present or future function is or is not a medical device. We do not claim FDA clearance, approval, authorization, certification, exemption, compliance, or endorsement. Intended use and regulatory status must be evaluated function by function with qualified clinical, regulatory, privacy, security, and legal review before live deployment."],
  ["6. User responsibilities and prohibited use", "You agree to use the site lawfully and only for its informational purpose. You may not rely on it for patient care; submit confidential or regulated data; misrepresent an affiliation, approval, or result; interfere with security; or use site content to operate a clinical system without written permission and independent validation."],
  ["7. Third-party sources and no endorsement", "Links and resources are provided for context. Inclusion does not imply sponsorship, endorsement, affiliation, adoption, or verification by the source organization. Third-party materials remain subject to their owners' terms, and users should consult the current official source rather than rely on our summary."],
  ["8. Intellectual property and feedback", "Patients Intelligence names, designs, software, demonstrations, and original content are protected by applicable intellectual-property laws. Limited personal or internal evaluation use does not transfer ownership. If you voluntarily provide non-confidential feedback, you grant us a worldwide, perpetual, irrevocable, royalty-free right to use it without identifying you or disclosing confidential information."],
  ["9. Disclaimer of warranties", "To the fullest extent permitted by law, the site is provided ‘as is’ and ‘as available,’ without warranties of accuracy, completeness, currency, availability, merchantability, fitness for a particular purpose, non-infringement, regulatory status, or outcome. We do not warrant that a prototype, proposed standard, planned entity, or future feature will become available."],
  ["10. Limitation of liability", "To the fullest extent permitted by law, Patients Intelligence, National Brand Group, and their owners, affiliates, personnel, and contractors will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, or for lost data, revenue, opportunity, goodwill, or patient outcomes arising from site use. Aggregate liability for any claim will not exceed the greater of $100 or the amount you paid us for use of this site during the preceding 12 months. Some jurisdictions do not permit certain limitations, so portions may not apply."],
  ["11. User indemnification", "To the fullest extent permitted by law, you agree to defend, indemnify, and hold harmless Patients Intelligence, National Brand Group, and their owners, affiliates, personnel, and contractors from third-party claims, losses, liabilities, damages, judgments, costs, and reasonable attorneys' fees arising from your prohibited submission of patient, health, confidential, or unlawful material; your misuse of the site; your violation of these terms; or your infringement of another person's rights. This does not apply to the extent a claim results from our gross negligence, willful misconduct, or conduct that cannot lawfully be indemnified."],
  ["12. Suspension, changes, and availability", "We may restrict or suspend access, remove content, or change the site and these terms to protect users, comply with law, or reflect product development. Material revisions will be identified by a new effective date. Continued use after an update constitutes acceptance where permitted by law."],
  ["13. Governing law, disputes, and severability", "Unless applicable law requires otherwise, these terms are governed by Massachusetts law, without regard to conflicts principles, and disputes will be brought in state or federal courts located in Massachusetts. If a provision is unenforceable, it will be narrowed to the minimum extent necessary and the remaining terms will continue."],
  ["14. Interim status", "Effective September 10, 2026. This is a risk-control draft for review by qualified health-technology counsel before any real patient intake, clinical pilot, data processing, or commercial deployment. No terms can guarantee immunity from claims or replace appropriate insurance, contracting, privacy review, security controls, and legal advice."],
];

export default function Terms() {
  return <PolicyPage title="Interim Terms of Use" lede="Clear boundaries for a public informational site: no clinical use, no patient submissions, and no implied regulatory status." sections={sections} />;
}
