import { AlertTriangle, PauseCircle, Scale, ShieldCheck } from "lucide-react";
import { CTASection, PageHero, SafetyNotice, SectionHeading, StatusTag, TrustStrip } from "@/components/site-shell";
import { InquiryForm } from "@/components/inquiry-form";
import { pilotPhases } from "@/app/data";

export const metadata = { title: "Clinical AI Intake Pilot", description: "A small, reversible co-design study of patient-originated AI intake and clinician review burden." };

export default function Pilot() {
  return <main id="main-content"><TrustStrip /><PageHero eyebrow="Pilot" title="A small, reversible study of a fast-growing workflow problem." lede="The pilot is a co-designed communication and workflow study—not an autonomous medicine deployment. It asks whether a structured Patient Intelligence Brief can reduce avoidable review burden while preserving patient voice, clinician authority, and timely escalation." status="proposed" />
    <section className="section"><div className="container"><div className="proposed-panel"><div><div className="eyebrow-row"><span className="eyebrow">Prospective case</span><StatusTag status="proposed" /></div><h2>Proposed MGB/BWH Foxborough co-design study</h2><p>Patients Intelligence has developed an ambulatory pilot framework for discussion with Dr. Ludwig and the Mass General Brigham / Brigham and Women’s Hospital Foxborough team.</p></div><aside><AlertTriangle /><strong>No endorsement implied</strong><p>This is not a signed or active institutional pilot. No approval, funding, adoption, or partnership is claimed, and no institutional logos are used.</p></aside></div></div></section>
    <section className="section pilot-phases"><div className="container"><SectionHeading eyebrow="Approximately 12 weeks / 90 days" title="Move only when the prior gate is satisfied." /><div className="phase-grid">{pilotPhases.map((item) => <article key={item.phase}><div><span className="phase-number">{item.phase}</span><StatusTag status={item.status} /></div><h3>{item.title}</h3><p>{item.detail}</p></article>)}</div></div></section>
    <section className="section measures-section"><div className="container"><SectionHeading eyebrow="Measurement plan" title="Measure burden, safety, usability, equity, and patient voice." /><div className="endpoint-grid"><article className="primary-endpoint"><span>Primary endpoint</span><h3>Clinician review minutes per AI-assisted message thread or encounter.</h3><p>The budget-relevant workflow measure—proposed, not yet validated.</p></article><article><span>Secondary</span><h3>Clarification burden</h3><p>Message volume, length, repeat exchanges, and workflow interruption.</p></article><article><span>Secondary</span><h3>Brief usefulness</h3><p>Completeness, source visibility, usability, and intercepted mismatches.</p></article><article><span>Experience</span><h3>Being heard</h3><p>Patient-reported understanding and acknowledgment.</p></article><article><span>Equity</span><h3>Access & performance</h3><p>Language, literacy, disability, and access findings under governance.</p></article></div></div></section>
    <section className="section dark-section"><div className="container stop-grid"><div><span className="eyebrow">Safety endpoint</span><h2>The institution retains pause and go/no-go authority.</h2><p>A missed urgent signal or introduced delay triggers pause, review, and redesign.</p></div><div>{[[PauseCircle, "Delayed or missed urgent signal"], [ShieldCheck, "Suppression or non-delivery"], [Scale, "Unsafe reliance or disparate performance"], [AlertTriangle, "Material privacy or security event"]].map(([Icon, text]) => { const I = Icon as typeof PauseCircle; return <p key={String(text)}><I />{String(text)}</p>; })}</div></div></section>
    <section className="section deliverables"><div className="container"><SectionHeading eyebrow="Decision-ready output" title="A pilot should create evidence, not dependency." /><div>{["Baseline workflow and burden map", "Co-designed protocol and synthetic demonstration", "Silent-validation results", "Limited-use evaluation, only if approved", "Safety and equity review", "Operational and procurement decision brief", "Research output only under approved authorship, privacy, IRB, and communications processes"].map((x, i) => <article key={x}><span>{String(i + 1).padStart(2, "0")}</span>{x}</article>)}</div></div></section>
    <section className="section form-section" id="co-design"><div className="container form-layout"><div><div className="eyebrow-row"><span className="eyebrow">First conversation</span><StatusTag status="proposed" /></div><h2>Request a 60-minute co-design session.</h2><p>Map one bounded intake problem, the current review burden, the institution’s governance gates, and what evidence would justify a silent validation phase.</p><SafetyNotice /></div><InquiryForm pilotOnly /></div></section><CTASection title="A small study can answer a consequential question." copy="Begin with current-state workflow, measurable burden, explicit boundaries, and the institution’s own stop rules." /></main>;
}
