import { AlertTriangle, Eye, FileClock, HeartHandshake, LockKeyhole, Scale, ShieldCheck, Users } from "lucide-react";
import { CTASection, PageHero, SectionHeading, StatusTag, TrustStrip } from "@/components/site-shell";
import { TrustFAQs } from "@/components/product-interactions";

export const metadata = { title: "Trust & Governance", description: "Inspectable safety, evidence, privacy, model neutrality, auditability, equity, and regulatory boundaries." };

const commitments = [
  [ShieldCheck, "Clinician primacy", "Qualified healthcare professionals retain judgment and duty of care. The system never finalizes diagnosis, treatment, code, or disposition."],
  [Eye, "Never-suppress architecture", "Every accepted submission remains visible to the designated clinical workflow. Labels affect routing, not whether a patient is heard."],
  [FileClock, "Evidence & uncertainty", "Assertions, sources, contradictions, gaps, unknowns, and transformations remain inspectable."],
  [Scale, "Model neutrality & drift", "Model, version, time, prompt context, and stated inputs are recorded. External benchmarks remain context, not permanent truth."],
  [LockKeyhole, "Privacy & sovereignty", "Data minimization, accurate pseudonymity, no advertising, no sale of patient-level data, and no health information in public forms."],
  [ShieldCheck, "Security by institutional design", "Controlled deployment, least privilege, encryption, logging, incident response, retention, and deletion are design requirements—not claimed certifications."],
  [FileClock, "Auditability & correction", "Submissions, transformations, profile states, views, acknowledgment, edits, and disposition are intended to be versioned and correctable."],
  [Users, "Equity & accessibility", "Language, literacy, disability, age, race, ethnicity, insurance status, and access patterns belong in evaluation under approved governance."],
] as const;

export default function Trust() {
  return <main id="main-content"><TrustStrip /><PageHero eyebrow="Trust & governance" title="Trust must be inspectable." lede="A healthcare AI workflow earns trust when its limits, evidence, human authority, correction paths, and operating status can be examined—not when they are hidden behind a confident score." />
    <section className="section"><div className="container commitment-list">{commitments.map(([Icon, title, copy], i) => <article key={title}><span className="commit-number">0{i + 1}</span><Icon /><div><h2>{title}</h2><p>{copy}</p></div></article>)}</div></section>
    <section className="section regulatory-section"><div className="container regulatory-grid"><div><div className="eyebrow-row"><span className="eyebrow">Regulatory posture</span><StatusTag status="proposed" /></div><h2>Intended use first. Function-by-function review before deployment.</h2><p>FDA’s Digital Health Policy Navigator evaluates each distinct software function according to its intended use; a product can contain functions with different regulatory treatment. Patients Intelligence is therefore being designed around narrow, documented functions—not a blanket regulatory conclusion.</p><p>Patients Intelligence does not claim that any function is exempt, non-device, compliant, cleared, approved, authorized, certified, or endorsed. A qualified, product-specific review must precede any clinical pilot or deployment.</p><small className="regulatory-review-date">Official sources last reviewed September 10, 2026.</small></div><aside><AlertTriangle /><h3>Official FDA source map</h3><p>These sources frame the current design review. They are not a formal FDA determination about Patients Intelligence.</p><div className="regulatory-source-map"><a href="https://www.fda.gov/medical-devices/digital-health-center-excellence/digital-health-policy-navigator" target="_blank" rel="noreferrer"><strong>Digital Health Policy Navigator</strong><span>Start with intended use and assess each software function.</span></a><a href="https://www.fda.gov/regulatory-information/search-fda-guidance-documents/clinical-decision-support-software" target="_blank" rel="noreferrer"><strong>Clinical Decision Support Software</strong><span>FDA final guidance, January 2026.</span></a><a href="https://www.fda.gov/regulatory-information/search-fda-guidance-documents/policy-device-software-functions-and-mobile-medical-applications" target="_blank" rel="noreferrer"><strong>Device Software Functions</strong><span>FDA oversight framework for software functions.</span></a></div></aside></div></section>
    <section className="section governance-section"><div className="container"><SectionHeading eyebrow="Intended operating model" title="Separate implementation, stewardship, validation, and education." copy="This is a staged architecture. Planned entities are not represented as incorporated, accredited, or operational." /><div className="governance-grid">{[["Patients Intelligence Technologies", "Commercial implementation", "Enterprise product development and implementation."], ["Patients AI Network", "Standards stewardship", "Planned nonprofit membership and convening body."], ["Patients Intelligence Institute", "Independent validation", "Planned research work with academic collaborators."], ["Patients Intelligence Academy", "Literacy & education", "Free patient literacy; future professional education subject to approval."]].map(([name, role, copy], i) => <article key={name}><span>0{i + 1}</span><small>{role}</small><h3>{name}</h3><p>{copy}</p><StatusTag status="forming" /></article>)}</div></div></section>
    <section className="section privacy-callout"><div className="container"><HeartHandshake /><div><span className="eyebrow">Patient-first architecture</span><h2>Do not punish incomplete sources or lower digital literacy with lower access to clinical attention.</h2><p>Uncertainty changes the label and may change the approved workflow. It never makes a patient less worthy of being heard.</p></div></div></section>
    <section className="section"><div className="container faq-layout"><div><SectionHeading eyebrow="Partner diligence" title="Questions we expect partners to ask." copy="The answers are deliberately bounded. Live use requires product-specific clinical, operational, legal, privacy, security, and institutional review." /></div><TrustFAQs /></div></section><CTASection title="Build trust into the workflow before live use." copy="Co-design the intended use, human gates, stop rules, evidence model, audit requirements, and correction paths with the institution that holds clinical responsibility." /></main>;
}
